/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as MissionMissionIdRouteImport } from './routes/mission.$missionId'
import { Route as PhotoPhotoIdRouteImport } from './routes/photo.$photoId'
import { Route as PhotographerSlugRouteImport } from './routes/photographer.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionMissionIdRoute = MissionMissionIdRouteImport.update({
  id: '/mission/$missionId',
  path: '/mission/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoPhotoIdRoute = PhotoPhotoIdRouteImport.update({
  id: '/photo/$photoId',
  path: '/photo/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographerSlugRoute = PhotographerSlugRouteImport.update({
  id: '/photographer/$slug',
  path: '/photographer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/saved': typeof SavedRoute
  '/upload': typeof UploadRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/photographer/$slug': typeof PhotographerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/saved': typeof SavedRoute
  '/upload': typeof UploadRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/photographer/$slug': typeof PhotographerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/saved': typeof SavedRoute
  '/upload': typeof UploadRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/photo/$photoId': typeof PhotoPhotoIdRoute
  '/photographer/$slug': typeof PhotographerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explore'
    | '/login'
    | '/missions'
    | '/saved'
    | '/upload'
    | '/mission/$missionId'
    | '/photo/$photoId'
    | '/photographer/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/explore'
    | '/login'
    | '/missions'
    | '/saved'
    | '/upload'
    | '/mission/$missionId'
    | '/photo/$photoId'
    | '/photographer/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explore'
    | '/login'
    | '/missions'
    | '/saved'
    | '/upload'
    | '/mission/$missionId'
    | '/photo/$photoId'
    | '/photographer/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  SavedRoute: typeof SavedRoute
  UploadRoute: typeof UploadRoute
  MissionMissionIdRoute: typeof MissionMissionIdRoute
  PhotoPhotoIdRoute: typeof PhotoPhotoIdRoute
  PhotographerSlugRoute: typeof PhotographerSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$missionId': {
      id: '/mission/$missionId'
      path: '/mission/$missionId'
      fullPath: '/mission/$missionId'
      preLoaderRoute: typeof MissionMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$photoId': {
      id: '/photo/$photoId'
      path: '/photo/$photoId'
      fullPath: '/photo/$photoId'
      preLoaderRoute: typeof PhotoPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographer/$slug': {
      id: '/photographer/$slug'
      path: '/photographer/$slug'
      fullPath: '/photographer/$slug'
      preLoaderRoute: typeof PhotographerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  SavedRoute: SavedRoute,
  UploadRoute: UploadRoute,
  MissionMissionIdRoute: MissionMissionIdRoute,
  PhotoPhotoIdRoute: PhotoPhotoIdRoute,
  PhotographerSlugRoute: PhotographerSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
